from __future__ import annotations

import unittest

from fastapi.testclient import TestClient

from pubg_ai.web.app import create_app


class WebReplayPlayerTests(unittest.TestCase):
    def test_index_includes_replay_player_controls(self) -> None:
        client = TestClient(create_app())
        response = client.get("/")

        self.assertEqual(response.status_code, 200)
        body = response.text
        self.assertIn("2D 리플레이 재생", body)
        self.assertIn('id="timelinePlayerForm"', body)
        self.assertIn('id="timelinePlayerClear"', body)
        self.assertIn('id="timelineSelect"', body)
        self.assertIn('id="timelineScrubber"', body)
        self.assertIn('id="timelineEventList"', body)
        self.assertIn('id="timelineEventDetail"', body)
        self.assertIn('id="timelineTeamList"', body)
        self.assertIn('id="timelineActorFilter"', body)
        self.assertIn('id="timelineEventTypeFilter"', body)
        self.assertIn('id="timelineFollowEvents"', body)
        self.assertIn('id="timelineEventFilterReset"', body)
        self.assertIn('id="timelineEventCount"', body)
        self.assertIn('id="timelineQuickEvents"', body)
        self.assertIn('id="timelineNowEvent"', body)
        self.assertIn('id="timelineShowTeam"', body)
        self.assertIn('id="timelineShowPhase"', body)
        self.assertIn('id="timelineFollowPlayer"', body)
        self.assertIn('id="timelineZoom"', body)
        self.assertIn('id="replayCanvas"', body)
        self.assertIn('id="replayArtifactListForm"', body)
        self.assertIn('id="replayArtifactPlayerSelect"', body)
        self.assertIn('id="replayArtifactsStatus"', body)
        self.assertIn('id="replayArtifactsCards"', body)
        self.assertIn("match_created_at_kst", body)
        self.assertIn("artifactTypeLabel", body)
        self.assertIn("loadSelectedTimeline", body)
        self.assertIn("loadReplayTimelinesForPlayer", body)
        self.assertIn("normalizeTimelineTiming", body)
        self.assertIn("canPlayTimelineArtifact", body)
        self.assertIn("validateTimelinePayload", body)
        self.assertIn("타임라인 시간축 또는 이동 구간이 손상되었습니다.", body)
        self.assertIn("version < 13", body)
        self.assertIn("재생성 필요", body)
        self.assertIn("time_origin_at_kst", body)
        self.assertIn("time_seconds", body)
        self.assertNotIn("Number(event?.t)", body)
        self.assertIn("renderTimelineTeamList", body)
        self.assertIn("drawReplayTeamTracks", body)
        self.assertIn("team_tracks", body)
        self.assertIn("timelineShowEngagements", body)
        self.assertIn("timelineShowShots", body)
        self.assertIn("timelineShowThrows", body)
        self.assertIn("timelineShowHits", body)
        self.assertIn("timelineShowDbno", body)
        self.assertIn("timelineShowKills", body)
        self.assertIn("drawReplayEngagements", body)
        self.assertIn("drawReplayCombatEvents", body)
        self.assertIn("drawThrowBurst", body)
        self.assertIn("timelineEventPresentation", body)
        self.assertIn("timelineEventMapPoint", body)
        self.assertIn("renderTimelineQuickEvents", body)
        self.assertIn("currentPlaybackTimelineEvent", body)
        self.assertIn("drawReplayCurrentEventCallout", body)
        self.assertIn("verified_opponent", body)
        self.assertIn("inferred_attack_activity", body)
        self.assertIn("drawDbnoMarker", body)
        self.assertIn("drawSquare", body)
        self.assertIn('data-timeline-map-event', body)
        self.assertIn('if (event.time > activeTimelineTime) break;', body)
        self.assertNotIn("nearestTimelineEvent", body)
        self.assertIn("movement_mode", body)
        self.assertNotIn("visibleEvents.slice(0, 400)", body)
        self.assertIn("시간대 분석", body)
        self.assertIn("상세 비교", body)
        self.assertIn("replayViewport", body)
        self.assertIn("replayViewportCenter", body)
        self.assertIn("replayZoom", body)
        self.assertIn("canvasPointVisible", body)
        self.assertIn("isReviveAction", body)
        self.assertIn("drawPlus", body)
        self.assertIn("revive_given", body)
        self.assertIn("revive_received", body)
        self.assertIn("phase_events", body)
        self.assertIn("drawReplayPhaseRings", body)
        self.assertIn("activePhaseEvent", body)
        self.assertIn("drawMapCircle", body)
        self.assertIn("renderReplayFrame", body)
        self.assertIn("timelineEvents", body)
        self.assertIn("combatRelatedLabel", body)
        self.assertIn("seekTimelineEvent", body)
        self.assertIn("loadReplayMapImage", body)
        self.assertIn("/replay/map-assets/", body)

    def test_index_includes_lookup_and_replay_section_anchors(self) -> None:
        client = TestClient(create_app())
        response = client.get("/")

        self.assertEqual(response.status_code, 200)
        body = response.text
        self.assertIn('id="registered-players"', body)
        self.assertIn('id="profile-lookup"', body)
        self.assertIn('id="weapon-lookup"', body)
        self.assertIn('id="recommendation-lookup"', body)
        self.assertIn('id="match-lookup"', body)
        self.assertIn('id="ranking-lookup"', body)
        self.assertIn('id="replay-player"', body)
        self.assertIn('id="replay-artifacts"', body)
        self.assertIn('id="playersBody"', body)
        self.assertIn("loadInitialLookupPrefillFromUrl", body)
        self.assertIn("lookup_target", body)
        self.assertIn("lookup_match_id", body)
        self.assertIn("replay_artifact_id", body)
        self.assertIn("replayArtifactFilter", body)
        self.assertIn("registeredPlayerHighlight", body)
        self.assertIn("ranking_metric", body)
        self.assertIn("ranking-lookup", body)

    def test_unknown_map_asset_returns_404(self) -> None:
        client = TestClient(create_app())
        response = client.get("/replay/map-assets/Unknown_Main")

        self.assertEqual(response.status_code, 404)


if __name__ == "__main__":
    unittest.main()
