from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Literal


MetricEvidence = Literal["telemetry", "participant", "derived"]


@dataclass(frozen=True)
class MetricDefinition:
    key: str
    label_ko: str
    category: str
    unit: str
    formula_ko: str
    denominator_ko: str
    source: str
    evidence: MetricEvidence
    caveat_ko: str = ""

    def to_record(self) -> dict[str, str]:
        return asdict(self)


_METRICS: tuple[MetricDefinition, ...] = (
    MetricDefinition(
        "win_rate",
        "치킨율",
        "survival",
        "%",
        "치킨 경기 수 / 집계 경기 수 x 100",
        "선택 필터를 통과한 경기",
        "match_participants.win_place",
        "participant",
    ),
    MetricDefinition(
        "top10_rate",
        "TOP 10 비율",
        "survival",
        "%",
        "10위 이내 경기 수 / 순위가 있는 경기 수 x 100",
        "win_place가 기록된 경기",
        "match_participants.win_place",
        "participant",
    ),
    MetricDefinition(
        "accuracy",
        "명중률",
        "combat",
        "%",
        "명중 횟수 / 일반 탄환 발사 추정 횟수 x 100",
        "전투 파서가 일반 탄환으로 분류한 발사",
        "player_match_combat_summaries",
        "telemetry",
        "샷건 펠릿과 일부 특수 무기는 별도 추정 규칙이 적용됩니다.",
    ),
    MetricDefinition(
        "headshot_hit_rate",
        "헤드샷 명중 비율",
        "combat",
        "%",
        "머리 명중 횟수 / 전체 명중 횟수 x 100",
        "실제로 맞춘 타격만 포함",
        "player_match_combat_summaries",
        "telemetry",
        "빗나간 탄환은 분모에 포함하지 않습니다.",
    ),
    MetricDefinition(
        "fight_win_rate",
        "교전 승리율",
        "combat",
        "%",
        "승리 교전 / 승패 판정이 가능한 교전 x 100",
        "킬 또는 기절 성공, 사망 또는 기절당함으로 판정된 교전",
        "player_fight_outcomes",
        "derived",
        "동일 교전의 후속 마무리와 부활은 교전 판정 규칙에 따라 중복 제거됩니다.",
    ),
    MetricDefinition(
        "avg_damage_dealt",
        "평균 준 피해",
        "combat",
        "damage/match",
        "총 준 피해 / 집계 경기 수",
        "선택 필터를 통과한 경기",
        "player_match_combat_summaries",
        "telemetry",
    ),
    MetricDefinition(
        "damage_ratio",
        "피해 교환비",
        "combat",
        "ratio",
        "총 준 피해 / 총 받은 피해",
        "선택 필터를 통과한 경기의 받은 피해 합계",
        "player_match_combat_summaries",
        "derived",
        "받은 피해가 0이면 분모를 1로 처리합니다.",
    ),
    MetricDefinition(
        "kills_per_10_minutes",
        "10분당 킬",
        "combat",
        "count/10min",
        "총 킬 / 유효 생존시간 x 600초",
        "timeSurvived가 양수인 경기의 생존시간 합계",
        "match_participants.raw_stats.timeSurvived",
        "derived",
        "비정상적으로 큰 생존시간은 해당 매치 duration_seconds로 제한합니다.",
    ),
    MetricDefinition(
        "damage_per_10_minutes",
        "10분당 준 피해",
        "combat",
        "damage/10min",
        "총 준 피해 / 유효 생존시간 x 600초",
        "timeSurvived가 양수인 경기의 생존시간 합계",
        "player_match_combat_summaries + match_participants",
        "derived",
        "비정상적으로 큰 생존시간은 해당 매치 duration_seconds로 제한합니다.",
    ),
    MetricDefinition(
        "fights_per_10_minutes",
        "10분당 교전",
        "combat",
        "count/10min",
        "승패 판정 교전 수 / 유효 생존시간 x 600초",
        "timeSurvived가 양수인 경기의 생존시간 합계",
        "player_fight_outcomes + match_participants",
        "derived",
    ),
    MetricDefinition(
        "damage_per_fight",
        "교전당 준 피해",
        "combat",
        "damage/fight",
        "총 준 피해 / 승패 판정 교전 수",
        "킬·가한 기절·사망·당한 기절로 승패 판정된 교전",
        "player_match_combat_summaries + player_fight_outcomes",
        "derived",
    ),
    MetricDefinition(
        "heal_amount",
        "총 체력 회복량",
        "support",
        "health",
        "모든 LogHeal.healAmount 합계(공식 문서의 healamount도 호환)",
        "행동 파서가 처리된 경기",
        "player_match_activity_summaries",
        "telemetry",
        "아이템 회복과 아이템 코드가 없는 부스트 지속 회복을 모두 포함합니다.",
    ),
    MetricDefinition(
        "item_heal_amount",
        "아이템 체력 회복량",
        "support",
        "health",
        "item.itemId가 있는 LogHeal.healAmount 합계(healamount 호환)",
        "행동 파서가 처리된 경기",
        "player_match_activity_summaries",
        "telemetry",
        "participant 통계의 heals는 사용 횟수이며 실제 회복량과 다릅니다.",
    ),
    MetricDefinition(
        "passive_heal_amount",
        "부스트 지속 회복량",
        "support",
        "health",
        "item.itemId가 없는 LogHeal.healAmount 합계(healamount 호환)",
        "행동 파서가 처리된 경기",
        "player_match_activity_summaries",
        "telemetry",
        "작은 회복 틱이 반복 기록되므로 이벤트 수를 아이템 사용 횟수로 해석하면 안 됩니다.",
    ),
    MetricDefinition(
        "revives_caused",
        "팀원 부활",
        "support",
        "count",
        "추적 플레이어가 reviver인 LogPlayerRevive 수",
        "행동 파서가 처리된 경기",
        "player_match_activity_summaries",
        "telemetry",
    ),
    MetricDefinition(
        "vehicle_distance_m",
        "차량 이동 거리",
        "mobility",
        "m",
        "LogVehicleLeave.rideDistance 합계",
        "행동 파서가 처리된 경기",
        "player_match_activity_summaries",
        "telemetry",
    ),
    MetricDefinition(
        "self_opening_rate",
        "선제 교전 비율",
        "decision",
        "%",
        "내 공격·피해 이벤트로 시작한 교전 에피소드 / 교전 에피소드 수 x 100",
        "교전 에피소드 파서가 식별한 교전",
        "player_fight_episodes.opening_actor",
        "derived",
        "공격 로그가 누락된 경우 첫 피해 이벤트를 기준으로 판정합니다.",
    ),
    MetricDefinition(
        "self_first_hit_rate",
        "선제 명중률",
        "decision",
        "%",
        "내가 첫 유효 피해를 준 교전 / 교전 에피소드 수 x 100",
        "피해 이벤트가 있는 교전 에피소드",
        "player_fight_episodes.first_hit_actor",
        "derived",
    ),
    MetricDefinition(
        "fight_accuracy",
        "교전 명중률",
        "decision",
        "%",
        "교전 중 캐릭터 명중 / 교전 중 일반 탄환 발사 추정 x 100",
        "교전 에피소드에 포함된 일반 탄환 발사",
        "player_fight_episodes",
        "derived",
        "차량과 환경 오브젝트 명중은 분자에서 제외됩니다.",
    ),
    MetricDefinition(
        "avg_fight_duration_seconds",
        "평균 교전 시간",
        "decision",
        "seconds",
        "교전 시작부터 마지막 관련 이벤트까지 시간 합계 / 교전 에피소드 수",
        "교전 에피소드",
        "player_fight_episodes.duration_seconds",
        "derived",
        "관련 이벤트 간격이 15초를 넘으면 별도 교전으로 분리합니다.",
    ),
    MetricDefinition(
        "avg_damage_advantage",
        "평균 피해 우위",
        "decision",
        "damage/fight",
        "교전별 (준 피해 - 받은 피해) 합계 / 교전 에피소드 수",
        "교전 에피소드",
        "player_fight_episodes",
        "derived",
    ),
    MetricDefinition(
        "knock_conversion_rate",
        "기절 후 킬 전환율",
        "decision",
        "%",
        "교전 킬 수 / 가한 기절 수 x 100",
        "가한 기절이 있는 교전",
        "player_fight_episodes",
        "derived",
        "팀원이 마무리한 기절은 개인 킬 전환으로 계산하지 않습니다.",
    ),
    MetricDefinition(
        "trade_rate",
        "팀 트레이드 성공률",
        "team",
        "%",
        "10초 안에 팀이 상대를 기절 또는 처치한 횟수 / 트레이드 기회 x 100",
        "나 또는 팀원이 적에게 기절·사망한 트레이드 기회",
        "player_fight_episodes + player_team_coordination_summaries",
        "derived",
    ),
    MetricDefinition(
        "third_party_rate",
        "제3팀 개입 비율",
        "decision",
        "%",
        "서로 다른 적 팀이 둘 이상 관측된 교전 / 교전 에피소드 수 x 100",
        "교전 에피소드",
        "player_fight_episodes.opponent_team_count",
        "derived",
    ),
    MetricDefinition(
        "blue_zone_exposure_seconds",
        "블루존 노출 시간",
        "rotation",
        "seconds",
        "isInBlueZone인 연속 위치 표본의 시간 간격 합계",
        "위치와 자기장 상태가 함께 기록된 페이즈",
        "player_zone_phase_summaries",
        "derived",
        "긴 위치 표본 간격은 과대 추정을 막기 위해 제한합니다.",
    ),
    MetricDefinition(
        "outside_safe_zone_seconds",
        "안전구역 밖 체류 시간",
        "rotation",
        "seconds",
        "안전구역 반경 밖 위치 표본의 시간 간격 합계",
        "안전구역 중심·반경과 플레이어 위치가 있는 페이즈",
        "player_zone_phase_summaries",
        "derived",
    ),
    MetricDefinition(
        "rotation_distance_m",
        "로테이션 거리",
        "rotation",
        "m",
        "페이즈 내 유효 연속 위치 사이 수평 거리 합계",
        "비정상 순간이동을 제외한 위치 표본",
        "player_zone_phase_summaries.rotation_distance_m",
        "derived",
    ),
    MetricDefinition(
        "vehicle_rotation_rate",
        "차량 로테이션 비중",
        "rotation",
        "%",
        "차량 이동 거리 / 전체 로테이션 거리 x 100",
        "로테이션 거리가 있는 페이즈",
        "player_zone_phase_summaries",
        "derived",
    ),
    MetricDefinition(
        "avg_late_entry_seconds",
        "평균 안전구역 진입 지연",
        "rotation",
        "seconds",
        "페이즈 시작 후 첫 안전구역 진입까지 시간 합계 / 진입이 관측된 페이즈",
        "안전구역 밖에서 시작해 안으로 진입한 페이즈",
        "player_zone_phase_summaries.late_entry_seconds",
        "derived",
    ),
    MetricDefinition(
        "avg_nearest_teammate_distance_m",
        "평균 최근접 팀원 거리",
        "team",
        "m",
        "각 위치 표본의 가장 가까운 생존 팀원 거리 합계 / 유효 표본 수",
        "같은 시점의 팀원 위치가 있는 표본",
        "player_team_coordination_summaries",
        "derived",
        "미래 위치를 사용하지 않으며 최대 15초 이내의 직전 위치만 사용합니다.",
    ),
    MetricDefinition(
        "isolated_seconds_per_match",
        "경기당 팀 고립 시간",
        "team",
        "seconds/match",
        "최근접 팀원이 150m보다 먼 시간 합계 / 팀 분석 경기 수",
        "팀원이 존재하고 위치 분석이 가능한 경기",
        "player_team_coordination_summaries.isolated_seconds",
        "derived",
    ),
    MetricDefinition(
        "avg_revive_latency_seconds",
        "평균 부활 지연",
        "team",
        "seconds",
        "기절부터 팀원 부활까지 시간 합계 / 부활 받은 횟수",
        "기절과 부활이 연결된 사례",
        "player_team_coordination_summaries",
        "derived",
    ),
    MetricDefinition(
        "avg_readiness_score",
        "평균 첫 교전 준비 점수",
        "loot",
        "score",
        "주무기 2개·조끼·헬멧·회복·조준경·투척물 확보 가중 점수 합계 / 파밍 분석 경기 수",
        "낙하 또는 아이템 획득 로그가 있는 경기",
        "player_loot_readiness_summaries.readiness_score",
        "derived",
        "최대 100점이며 아이템 품질이나 탄약량까지 완전 평가하는 점수는 아닙니다.",
    ),
    MetricDefinition(
        "ready_before_first_fight_rate",
        "첫 교전 전 준비 완료율",
        "loot",
        "%",
        "필수 장비를 첫 교전 전에 확보한 경기 / 첫 교전 시점이 있는 경기 x 100",
        "첫 교전과 파밍 로그가 모두 있는 경기",
        "player_loot_readiness_summaries.ready_before_first_fight",
        "derived",
    ),
    MetricDefinition(
        "full_primary_loadout_rate",
        "주무기 2개 확보율",
        "loot",
        "%",
        "서로 다른 주무기 2개를 획득한 경기 / 파밍 분석 경기 x 100",
        "파밍 분석 경기",
        "player_loot_readiness_summaries.second_primary_weapon_code",
        "derived",
    ),
    MetricDefinition(
        "activity_coverage",
        "행동 분석 커버리지",
        "quality",
        "%",
        "현재 활동 파서 버전 처리 경기 / 원본 텔레메트리가 있는 대상 경기 x 100",
        "원본 텔레메트리가 저장된 선택 경기",
        "player_telemetry_processing_states",
        "derived",
        "100% 미만이면 행동 지표의 0은 실제 0이 아니라 미처리일 수 있습니다.",
    ),
)


def metric_catalog_records(*, category: str | None = None) -> list[dict[str, str]]:
    normalized_category = str(category or "").strip().lower()
    definitions = _METRICS
    if normalized_category:
        definitions = tuple(row for row in definitions if row.category == normalized_category)
    return [definition.to_record() for definition in definitions]


def metric_definition(key: str) -> MetricDefinition | None:
    normalized = str(key or "").strip()
    return next((definition for definition in _METRICS if definition.key == normalized), None)
